version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/pgp-june
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  BeforeAllowTraffic:
    - location: scripts/start.sh
      timeout: 300
      runas: root
