custombucket = "zendrix-upload"
table = "zendrix_tb"
databasehost = "zendrix-rds.cbhab2gjsoyk.us-east-1.rds.amazonaws.com"
duser = "zendrix_user"
dpass = "zendrix123"
s3database = "zendrixdb"
kapp = "http://192.168.3.57:30000"
