apiVersion: v1
kind: Service
metadata:
  name: zendrix-service
  labels:
    app: zendrix
spec:
  type: NodePort
  selector:
    app: zendrix
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30000
